### ISSUE TITLE
Magento 2.2 - Notice: Undefined index: children in Reader.php on line 161

### ISSUE THREAD

**Issue by pixiesky** [astorm/magento2-simple-ui-component#1] opened 2017-10-24 16:57 UTC
(I don't know how best to report this to you so I am doing it here).

Running through the tutorial with 2.2 I got the following:

```
1 exception(s):
Exception #0 (Exception): Notice: Undefined index: children in /home/andy/www/magento2.dev/vendor/magento/module-ui/Config/Reader.php on line 161

Exception #0 (Exception): Notice: Undefined index: children in /home/andy/www/magento2.dev/vendor/magento/module-ui/Config/Reader.php on line 161
#0 /home/andy/www/magento2.dev/vendor/magento/module-ui/Config/Reader.php(161): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/home/andy/www/...', 161, Array)
#1 /home/andy/www/magento2.dev/vendor/magento/module-ui/Config/Reader.php(147): Magento\Ui\Config\Reader->mergeDefinition(Array, Array)
#2 /home/andy/www/magento2.dev/vendor/magento/module-ui/Config/Reader.php(101): 
...
etc
```
I tried pasting in the "first pass example" in place of my follow-along effort and I get the same result. The second pass works once we change `Pulsestorm/SimpleUiComponent/view/adminhtml/ui_component/pulsestorm_simple.xml`. As my understanding is limited I do not really know any more than that.

Thanks.

**Comment by astorm** [comment] 2017-10-25 00:55
@pixiesky thanks for the heads up.  Which tutorial were you following along in?

**Comment by pixiesky** [comment] 2017-10-25 08:05
Oh sorry I was in ~http://alanstorm.com/magento_2_simplest_ui_knockout_component/~

**Comment by astorm** [comment] 2017-10-25 14:43
Thank you @pixiesky -- do you remember the last code change/copy-paste you made right before you got that error?

**Comment by pixiesky** [comment] 2017-10-25 19:12
Nope, I was actually in http://alanstorm.com/magento_simplest_ui_component/ 

I don't know and I'm struggling to get the same result now. I've tired again and got quite far in the tutorial and I can't seem to make it happen I must have messed up somewhere. My memory tells me it was after `view/base/ui_component/etc/definition.xml` 

But I've noticed something earlier on. If I do this ...

* Enter the pestle commands, cleared cache and got to this stage.
![selection_011](https://user-images.githubusercontent.com/2039456/32017730-8abc0894-b9bf-11e7-997c-1794e1c4ab9e.png)

* Updated `app/code/Pulsestorm/SimpleUiComponent/view/adminhtml/layout/pulsestorm_simpleuicomponent_index_index.xml`

```xml
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <referenceBlock name="content">
        <block template="content.phtml" class="Pulsestorm\SimpleUiComponent\Block\Adminhtml\Main" name="pulsestorm_simpleuicomponent_block_main" />

        <!-- START: our new ui component -->
        <uiComponent name="pulsestorm_simple"/>
        <!-- END:   our new ui component -->
    </referenceBlock>
</page>
```
Clear cache

I get error:
```
Fatal error:  Uncaught TypeError: Argument 2 passed to Magento\Framework\View\Element\UiComponentFactory::argumentsResolver() must be of the type array, null given, called in /home/andy/www/magento2.dev/vendor/magento/framework/View/Element/UiComponentFactory.php on line 198 and defined in /home/andy/www/magento2.dev/vendor/magento/framework/View/Element/UiComponentFactory.php:164
Stack trace:
#0 /home/andy/www/magento2.dev/vendor/magento/framework/View/Element/UiComponentFactory.php(198): Magento\Framework\View\Element\UiComponentFactory->argumentsResolver('pulsestorm_simp...', NULL)
#1 /home/andy/www/magento2.dev/vendor/magento/framework/View/Layout/Generator/UiComponent.php(135): Magento\Framework\View\Element\UiComponentFactory->create('pulsestorm_simp...', NULL, Array)
#2 /home/andy/www/magento2.dev/vendor/magento/framework/View/Layout/Generator/UiComponent.php(97): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'pulsestorm_simp...', Array,  in /home/andy/www/magento2.dev/vendor/magento/framework/View/Element/UiComponentFactory.php on line 164
```

I can recreate the error by pasting in https://github.com/astorm/magento2-simple-ui-component/tree/master/first-pass-unstable/app/code/Pulsestorm/SimpleUiComponent

`Exception #0 (Exception): Notice: Undefined index: children in /home/andy/www/magento2.dev/vendor/magento/module-ui/Config/Reader.php on line 161`

**Comment by jonathanholt** [comment] 2017-11-29 12:13
Hi @pixiesky & @astorm ,
I am working on Magento 2.2.1 and I got the same error mentioned in the original post when I followed along with the tutorial (Magento 2: Simplest UI Component).
I also manually installed the "first-pass-unstable" from this repo and got the same error.

Changing the 'pulsestorm_simple' node to 'container' inside of view/adminhtml/ui_component/pulsestorm_simple.xml got it working.

```xml
<container xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <argument name="data" xsi:type="array">
        <item name="template" xsi:type="string">templates/different</item>
    </argument>

    <dataSource name="pulsestorm_simple_data_source">                        
        <argument name="dataProvider" xsi:type="configurableObject">
            <!-- the PHP class that implements a data provider -->
            <argument name="class" xsi:type="string">Pulsestorm\SimpleUiComponent\Model\DataProvider</argument>    
 
            <!-- redundant with the `dataSource` name -->
            <argument name="name" xsi:type="string">pulsestorm_simple_data_source</argument>
 
            <!-- required: means ui components are meant to work with models -->
            <argument name="primaryFieldName" xsi:type="string">entity_id</argument>
 
            <!-- required: means ui components are meant to work with URL passing -->
            <argument name="requestFieldName" xsi:type="string">id</argument>
        </argument>        
 
    </dataSource>
</container>
```

**Comment by astorm** [comment] 2017-12-24 05:44
Just making a note here that this module does appear to be busted in Magento 2.2.  Simply installing  the `Pulsestorm_SimpleUiComponent` module from the `first-pass-unstable` folder results in the 

> Exception #0 (Exception): Notice: Undefined index: children in /Users/alanstorm/Sites/magento-2-2-x.dev/magento2/vendor/magento/module-ui/Config/Reader.php on line 162

> Exception #0 (Exception): Notice: Undefined index: children in /Users/alanstorm/Sites/magento-2-2-x.dev/magento2/vendor/magento/module-ui/Config/Reader.php on line 162

errors when loading the `admin/pulsestorm_simpleuicomponent/index/index` URI.

I'm uncertain when/if I'll be able to figure out if this is possible to fix.  Per the README, it looks like this  module still works in 2.1.1

> Code samples are currently tested against Magento 2.1.1. Hopefully the techniques hold solid. See the Simplest UI Component article, other others in the series, for more context.

For anyone coming along later who hasn't been able to find a fix for this -- I'd recommend working through the tutorial with Magento 2.1.1.

**Comment by astorm** [comment] 2017-12-24 06:36
Another random note -- it looks like the problem is here:

    vendor/magento/module-ui/Config/Converter.php

This file builds a "schemaMap" by reading from 

    vendor/magento/module-ui/view/base/ui_component/etc/definition.map.xml

My guess is because this file doesn't have a `pulsestorm_simple` in it, the problematic `children` node doesn't get populated and Magento gets sad.

**Closed as completed** 2017-12-24 06:50 UTC

**Comment by astorm** [comment] 2017-12-24 06:57
@pixiesky FYI -- managed to fix this in the following PR: https://github.com/astorm/magento2-simple-ui-component/pull/3  Magento 2 introduced a new `definition.map.xml` file that serves an uncertain purpose.  Not having a `pulsestorm_simple` node in there resulted in an array being populated without a `children` key, which resulting in the error you saw.

**Comment by pixiesky** [comment] 2018-03-27 12:23
@astorm I've been busy so didn't follow this but I'm very pleased to see it sorted. I will try going through it again now. Thanks.
